ruby '2.6.5'
source 'https://rubygems.org'
gem 'sinatra'
gem 'activerecord', '>= 6.0.3.5'
gem 'sinatra-activerecord', '>= 2.0.14'
gem 'pg'
gem 'sinatra-websocket'
gem 'json'
gem 'will_paginate'
gem 'rake'
